extends Node

class_name Movimentos

enum MOVIMENTS {FRONT,BEHIND,LEFT,RIGHT,ACTION,SQUAT,JUMP}
const MOVIMENT_FAIL = "Fail"
const MOVIMENTS_RESULT = {
	"SIMPLES_EXECUTION" : [[MOVIMENTS.ACTION]],
	"BRUTE_EXECUTION" : [[MOVIMENTS.SQUAT,MOVIMENTS.ACTION]],
	"MANEJO_DOWN" : [
		[MOVIMENTS.FRONT,MOVIMENTS.ACTION],
		[MOVIMENTS.BEHIND,MOVIMENTS.ACTION],
		[MOVIMENTS.LEFT,MOVIMENTS.ACTION],
		[MOVIMENTS.RIGHT,MOVIMENTS.ACTION]
	],
	"ESTOCADA" : [
		[MOVIMENTS.FRONT,MOVIMENTS.FRONT,MOVIMENTS.ACTION],
		[MOVIMENTS.BEHIND,MOVIMENTS.BEHIND,MOVIMENTS.ACTION],
		[MOVIMENTS.LEFT,MOVIMENTS.LEFT,MOVIMENTS.ACTION],
		[MOVIMENTS.RIGHT,MOVIMENTS.RIGHT,MOVIMENTS.ACTION]
	],
	"MANEJO_ABERTO_LATERAL" : [
		[MOVIMENTS.FRONT,MOVIMENTS.BEHIND,MOVIMENTS.ACTION],
		[MOVIMENTS.BEHIND,MOVIMENTS.FRONT,MOVIMENTS.ACTION],
		[MOVIMENTS.LEFT,MOVIMENTS.RIGHT,MOVIMENTS.ACTION],
		[MOVIMENTS.RIGHT,MOVIMENTS.LEFT,MOVIMENTS.ACTION]
	],
	"MANEJO_FECHADO_LATERAL" : [
		[MOVIMENTS.FRONT,MOVIMENTS.LEFT,MOVIMENTS.ACTION],
		[MOVIMENTS.LEFT,MOVIMENTS.FRONT,MOVIMENTS.ACTION],
		[MOVIMENTS.BEHIND,MOVIMENTS.LEFT,MOVIMENTS.ACTION],
		[MOVIMENTS.LEFT,MOVIMENTS.BEHIND,MOVIMENTS.ACTION],
		[MOVIMENTS.RIGHT,MOVIMENTS.BEHIND,MOVIMENTS.ACTION],
		[MOVIMENTS.BEHIND,MOVIMENTS.RIGHT,MOVIMENTS.ACTION],
		[MOVIMENTS.RIGHT,MOVIMENTS.FRONT,MOVIMENTS.ACTION],
		[MOVIMENTS.FRONT,MOVIMENTS.RIGHT,MOVIMENTS.ACTION]
	]
}

static func sameSequence(seq1,seq2):
	for m in seq2.size():
		if seq1[m] != seq2[m]:
			return false
	return true

static func get_moviment_sequence_result(seq1):
	for m in Movimentos.MOVIMENTS_RESULT.keys():
		if seq1.size() == Movimentos.MOVIMENTS_RESULT[m][0].size():
			for seq in Movimentos.MOVIMENTS_RESULT[m]:
				if Movimentos.sameSequence(seq1,seq):
					return m
	return MOVIMENT_FAIL

static func isMovimentExecution(mov):
	return mov == Movimentos.MOVIMENTS.ACTION
